# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: Matech04/astro-decap
  branch: main
  identity_url: https://auth.decapbridge.com/sites/22602d59-239f-4890-bbcd-7d326fd5311f
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: http://localhost:4321

media_folder: src/assets/img
public_folder: src/assets/img
registerMediaLibrary:
  name: local # Use local storage for simplicity; change to 'uploadcare' if needed

i18n:
  structure: multiple_folders
  locales: [en, de, pl]
  default_locale: en

collections:
  - name: translations
    label: Tłumaczenia
    i18n:
      structure: single_file
      locales: [en, de, pl]
    files:
      - name: home
        label: Strona Główna
        file: src/content/translations/home.md
        format: frontmatter
        i18n: true
        fields:
          - label: Tytuł 1
            name: title1
            widget: string
            i18n: true
          - label: Tytuł 2
            name: title2
            widget: string
            i18n: true
          - label: Opis 1
            name: description1
            widget: text
            i18n: true
          - label: Opis 2
            name: description2
            widget: text
            i18n: true
          - label: Przycisk
            name: button
            widget: string
            i18n: true
          - label: Karty
            name: cards
            widget: list
            i18n: true
            fields:
              - label: Tytuł Karty
                name: title
                widget: string
                i18n: true
              - label: Opis Karty
                name: description
                widget: text
                i18n: true
          - label: O Nas
            name: about
            widget: object
            i18n: true
            fields:
              - label: Tytuł O Nas
                name: title
                widget: string
                i18n: true
              - label: Opis O Nas
                name: description
                widget: text
                i18n: true
          - label: Projekty
            name: projects
            widget: object
            i18n: true
            fields:
              - label: Tytuł Projektów
                name: title
                widget: string
                i18n: true
              - label: Przycisk Projektów
                name: button
                widget: string
                i18n: true
      - name: navigation
        label: Nawigacja
        file: src/content/translations/navigation.md
        format: frontmatter
        i18n: true
        fields:
          - label: Strona Główna
            name: home
            widget: string
            i18n: true
          - label: Projekty
            name: projects
            widget: string
            i18n: true
          - label: Kontakt
            name: contact
            widget: string
            i18n: true
          - label: Polityka Prywatności
            name: rules
            widget: string
            i18n: true
      - name: contact
        label: Formularz Kontaktowy
        file: src/content/translations/contact.md
        format: frontmatter
        i18n: true
        fields:
          - label: Tytuł 1
            name: title1
            widget: string
            i18n: true
          - label: Tytuł 2
            name: title2
            widget: string
            i18n: true
          - label: Opis
            name: description
            widget: text
            i18n: true
          - label: Formularz
            name: form
            widget: object
            i18n: true
            fields:
              - label: Imię
                name: name
                widget: string
                i18n: true
              - label: Adres e-mail
                name: email
                widget: string
                i18n: true
              - label: Numer telefonu
                name: phone
                widget: string
                i18n: true
              - label: Przycisk
                name: button
                widget: string
                i18n: true
