# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: Matech04/astro-decap
  branch: main
  identity_url: https://auth.decapbridge.com/sites/22602d59-239f-4890-bbcd-7d326fd5311f
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: http://localhost:4321

media_folder: src/assets/img
public_folder: src/assets/img
registerMediaLibrary:
  name: local # Use local storage for simplicity; change to 'uploadcare' if needed

i18n:
  structure: multiple_folders
  locales: [en, de, pl]
  default_locale: en

collections:
  - name: translations
    label: Tłumaczenia
    i18n:
      structure: single_file
    folder: src/content/translations
    files:
      - name: navigation
        label: Nawigacja
        file: navigation.md
        fields:
          - {
              label: "Strona Główna",
              name: "home",
              widget: "string",
              i18n: true,
            }
          - {
              label: "Projekty",
              name: "projects",
              widget: "string",
              i18n: true,
            }
          - { label: "Kontakt", name: "contact", widget: "string", i18n: true }
          - {
              label: "Polityka Prywatności",
              name: "rules",
              widget: "string",
              i18n: true,
            }
